"""sync dossiers table

Revision ID: 326a0e302a4f
Revises: 
Create Date: 2026-04-19 02:12:07.594087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '326a0e302a4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dossiers', sa.Column('adresse1', sa.String(), nullable=True))
    op.add_column('dossiers', sa.Column('adresse2', sa.String(), nullable=True))
    op.add_column('dossiers', sa.Column('tel_fixe', sa.String(), nullable=True))
    op.add_column('dossiers', sa.Column('tel_port', sa.String(), nullable=True))
    op.add_column('dossiers', sa.Column('resp_nom', sa.String(), nullable=True))
    op.add_column('dossiers', sa.Column('resp_tel', sa.String(), nullable=True))
    op.add_column('dossiers', sa.Column('resp_email', sa.String(), nullable=True))
    op.add_column('dossiers', sa.Column('forme', sa.String(), nullable=True))
    op.add_column('dossiers', sa.Column('nom_commercial', sa.String(), nullable=True))
    op.add_column('dossiers', sa.Column('date_creation', sa.String(), nullable=True))
    op.add_column('dossiers', sa.Column('date_cloture', sa.String(), nullable=True))
    op.alter_column('dossiers', 'num_dossier',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint(op.f('dossiers_database_name_key'), 'dossiers', type_='unique')
    op.create_index(op.f('ix_dossiers_id'), 'dossiers', ['id'], unique=False)
    op.create_index(op.f('ix_dossiers_num_dossier'), 'dossiers', ['num_dossier'], unique=False)
    op.drop_column('dossiers', 'schema_version')
    op.drop_column('dossiers', 'tel')
    op.drop_column('dossiers', 'responsable_email')
    op.drop_column('dossiers', 'responsable_tel')
    op.drop_column('dossiers', 'responsable')
    op.drop_column('dossiers', 'denomination')
    op.drop_column('dossiers', 'forme_juridique')
    op.drop_column('dossiers', 'created_at')
    op.drop_column('dossiers', 'database_name')
    op.drop_column('dossiers', 'port')
    op.drop_column('dossiers', 'tva2')
    op.drop_column('dossiers', 'hameau')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dossiers', sa.Column('hameau', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('dossiers', sa.Column('tva2', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('dossiers', sa.Column('port', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('dossiers', sa.Column('database_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('dossiers', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('dossiers', sa.Column('forme_juridique', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('dossiers', sa.Column('denomination', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('dossiers', sa.Column('responsable', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('dossiers', sa.Column('responsable_tel', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('dossiers', sa.Column('responsable_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('dossiers', sa.Column('tel', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('dossiers', sa.Column('schema_version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_dossiers_num_dossier'), table_name='dossiers')
    op.drop_index(op.f('ix_dossiers_id'), table_name='dossiers')
    op.create_unique_constraint(op.f('dossiers_database_name_key'), 'dossiers', ['database_name'], postgresql_nulls_not_distinct=False)
    op.alter_column('dossiers', 'num_dossier',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('dossiers', 'date_cloture')
    op.drop_column('dossiers', 'date_creation')
    op.drop_column('dossiers', 'nom_commercial')
    op.drop_column('dossiers', 'forme')
    op.drop_column('dossiers', 'resp_email')
    op.drop_column('dossiers', 'resp_tel')
    op.drop_column('dossiers', 'resp_nom')
    op.drop_column('dossiers', 'tel_port')
    op.drop_column('dossiers', 'tel_fixe')
    op.drop_column('dossiers', 'adresse2')
    op.drop_column('dossiers', 'adresse1')
    # ### end Alembic commands ###
